-- Chạy trong Supabase: SQL Editor → New query → Run
-- Sau đó copy Project URL + service_role key vào backend/.env

create table if not exists public.command_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null,
  session_id text,
  role text not null,
  content text,
  tool_name text,
  tool_args text,
  tool_result text,
  meta text
);

comment on table public.command_log is 'Lịch sử chat / lệnh tool agent (đồ án pentest MVP)';

-- Service role (backend) bỏ qua RLS. Nếu sau này dùng anon từ browser, bật RLS và thêm policy phù hợp.
alter table public.command_log enable row level security;


-- ═══ Bảng lưu trạng thái WSTG Checklist ═══
create table if not exists public.wstg_results (
  id bigint generated by default as identity primary key,
  wstg_id text not null unique,           -- VD: WSTG-INFO-01
  status text not null default 'not_started', -- not_started | pass | issue
  target_url text,                        -- URL mục tiêu đã quét
  result_summary text,                    -- Tóm tắt kết quả (max 4000 ký tự)
  updated_at timestamptz not null default now()
);

comment on table public.wstg_results is 'Trạng thái kiểm thử OWASP WSTG Checklist';
alter table public.wstg_results enable row level security;
