-- Chạy trong Supabase: SQL Editor → New query → Run
-- Sau đó copy Project URL + service_role key vào backend/.env

create table if not exists public.command_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null,
  session_id text,
  role text not null,
  content text,
  tool_name text,
  tool_args text,
  tool_result text,
  meta text
);

comment on table public.command_log is 'Lịch sử chat / lệnh tool agent (đồ án pentest MVP)';

-- Service role (backend) bỏ qua RLS. Nếu sau này dùng anon từ browser, bật RLS và thêm policy phù hợp.
alter table public.command_log enable row level security;
