-- Chạy trong Supabase: SQL Editor → New query → Run
-- Sau đó copy Project URL + service_role key vào backend/.env

create table if not exists public.command_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null,
  session_id text,
  role text not null,
  content text,
  tool_name text,
  tool_args text,
  tool_result text,
  wstg_id text,
  meta text
);

comment on table public.command_log is 'Lịch sử chat / lệnh tool agent (đồ án pentest MVP)';

-- Service role (backend) bỏ qua RLS. Nếu sau này dùng anon từ browser, bật RLS và thêm policy phù hợp.
alter table public.command_log enable row level security;


-- ═══ Bảng lưu trạng thái WSTG Checklist ═══
create table if not exists public.wstg_results (
  id bigint generated by default as identity primary key,
  wstg_id text not null unique,           -- VD: WSTG-INFO-01
  status text not null default 'not_started', -- not_started | pass | issue | needs_review
  target_url text,                        -- URL mục tiêu đã quét
  result_summary text,                    -- Tóm tắt kết quả (max 4000 ký tự)
  updated_at timestamptz not null default now()
);

comment on table public.wstg_results is 'Trạng thái kiểm thử OWASP WSTG Checklist';
alter table public.wstg_results enable row level security;


-- ═══ Bảng lưu Knowledge Base WSTG (RAG Vector Search) ═══
-- Yêu cầu: Bật extension pgvector trước khi chạy
-- create extension if not exists vector;

create table if not exists public.wstg_kb (
  id bigint generated by default as identity primary key,
  wstg_id text,                             -- VD: WSTG-INFO-01
  content text not null,                    -- Nội dung tài liệu WSTG
  embedding vector(768),                    -- Vector embedding (768 dimensions cho text-embedding-004)
  metadata jsonb default '{}'::jsonb        -- Metadata bổ sung
);

comment on table public.wstg_kb is 'Knowledge Base OWASP WSTG v4.2 với vector embeddings cho RAG';
alter table public.wstg_kb enable row level security;

-- Index cho vector similarity search
create index if not exists wstg_kb_embedding_idx
  on public.wstg_kb using ivfflat (embedding vector_cosine_ops)
  with (lists = 10);


-- ═══ RPC Function: Vector Similarity Search ═══
create or replace function public.match_wstg_kb(
  query_embedding vector(768),
  match_threshold float default 0.7,
  match_count int default 5
)
returns table (
  id bigint,
  wstg_id text,
  content text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    wstg_kb.id,
    wstg_kb.wstg_id,
    wstg_kb.content,
    1 - (wstg_kb.embedding <=> query_embedding) as similarity
  from public.wstg_kb
  where 1 - (wstg_kb.embedding <=> query_embedding) > match_threshold
  order by wstg_kb.embedding <=> query_embedding
  limit match_count;
end;
$$;
